---
title: "Reproducible Research: Peer Assessment 1"
author: "Ima"
date: "Monday, February 06, 2017"
output: html_document
---
```{r libLoad, message=FALSE, warning=FALSE}
library(gdata)
library(ggplot2)
```

```{r loadData, echo=TRUE}
## Load and preprocessing the data
unzip('M:/R/activity.zip')
data <- read.csv('M:/R/activity.csv', header= TRUE)
```

```{r meanPerDay, echo=TRUE}
## What is mean total number of steps taken per day?
totalSteps <- tapply(data$steps, data$date, FUN=sum, na.rm=TRUE)
qplot(totalSteps, binwidth=1000, xlab="total number of steps per day")
mean(totalSteps, na.rm=TRUE)
median(totalSteps,na.rm=TRUE)
```

```{r averageDaily, echo=TRUE}
## What is the average daily activity pattern?
averages <- aggregate(x=list(steps=data$steps), by=list(interval=data$interval), FUN=mean, na.rm=TRUE)
ggplot(data=averages, aes(x=interval, y=steps))+ geom_line() +xlab("5 minute interval") +ylab("average number of steps taken")
averages[which.max(averages$steps),]
```
```{r imputeMissing, echo=TRUE}
## Imputing missing values
missing <- is.na(data$steps)
table(missing)
fill.value <- function(steps, interval){
filled <- NA
if (!is.na(steps))
  filled <- c(steps)
else
  filled <- (averages[averages$interval==interval, "steps"])
return(filled)
}
filled.data <- data
filled.data$steps <- mapply(fill.value, filled.data$steps, filled.data$interval)
```

```{r weekDaysEnds, echo=TRUE}
## Are there differences in activity patterns between weekdays and weekends?
total.steps <- tapply(filled.data$steps, filled.data$date, FUN=sum)
qplot(total.steps, binwidth=1000, xlab="total number of steps taken per day")
mean(total.steps)
median(total.steps)

weekdayorweekend <- function(date){
 day <- weekdays(date)
 if (day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
   return("weekday")
 else if (day %in% c("Saturday", "Sunday"))
   return("weekend")
 else
   stop("invalid date")
 }
filled.data$date <- as.Date(filled.data$date)
filled.data$day <- sapply(filled.data$date, FUN=weekdayorweekend)

averages <- aggregate(steps ~ interval + day, data=filled.data, mean)
ggplot(averages, aes(interval, steps))+ geom_line()+ facet_grid(day ~ .)+ xlab("5-minute interval")+ ylab("Number of steps")
```

